panditakshay402/Hacktoberfest

- C++/mostOptimalBFS.cpp
- C++/printnameNtimes.cpp
> Print ntimes

- C++/mostOptimalBFS.cpp
Added cpp code along with explanation
> added-mostOptimalBFS

- C/Right-Triangle-Pattern.c
**Pull Request Title:** Add Right-Angled Triangle Pattern
**Pull Request Description:**
This pull request adds the implementation of a right-angled triangle pattern in the `Right-Triangle-Pattern.c` file. Users can specify the number of rows for the right-angled triangle, and the program will print the pattern accordingly.
- Implemented the logic for generating the right-angled triangle using nested loops.
#4
> addded right traingle pattern

- C/Pattern5.c
> new pattern added

- C++/SelectionSort.cpp
> Added selection sort

- PYTHON/calculator.py
Please merge the PR to hacktoberfest.
> Create calculator by python

- JAVA/DYNAMIC_PROGRAMMING/ UniquePaths.java
- JAVA/DYNAMIC_PROGRAMMING/IntegerBreak.java
- JAVA/DYNAMIC_PROGRAMMING/JumpGame.java
- JAVA/DYNAMIC_PROGRAMMING/MaximumProductSubarray.java
- JAVA/DYNAMIC_PROGRAMMING/MaximumSubarray.java
Added a folder in java section "DYNAMIC PROGRAMMING"
added few standard DP problems in that folder.
@panditakshay402 please do add necessory labels such as "hactoberfest" "hacktoberfest-accepted" to that the contibution counted.
> Added Dynamic Programming Problems

- JavaScript/TelephoneNumberValidator
Added JavaScript folder.
Added TelephoneNumberValidator code to JavaScript folder.
> added JS folder and one project

- C++/Stack.cpp/Area of largest rectangle in Histogram.cpp
- C++/Stack.cpp/AsteroidCollision.cpp
- C++/Stack.cpp/CelebrityProblem.cpp
- C++/Stack.cpp/NextGreaterElement.cpp
Added few extra-ordinary questions of Stack.
> added few stack questions

- C++/N _times_names.cpp
Added the problem file,pls merge it
> N times name file added

- Spiral Matrix
please assign me soo i can contribute more matrix problems and their solution.
> Create Spiral Matrix

- Median of Two Sorted Arrays
#33 please assign me this issue. i like to contribute many number of important codes of array.
> Create Median of Two Sorted Arrays

- PYTHON/password_protected_pdf.py
- PYTHON/pdf_merger.py
Hey buddy! I have added two basic python codes namely pdfmerger.py and password_protected_pdf.py. Do consider the project and merge it if you like it.
> Added two basic python codes.

- JAVA/BinarySearch.java
- JAVA/DoublyLinkedList.java
- JAVA/LinkedList.java
> Binary Search Added

- .vscode/launch.json
- JAVA/LinkedList/LinkedListPailendrom.java
- JAVA/LinkedList/LinkedListSize.java
> Linked List

- C++/Best Time to Buy and Sell Stock with Transaction Fee.cpp
**Problem**: Create Best Time to Buy and Sell Stock with Transaction Fee
**Problem link**: https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-transaction-fee/description/
**Method**: Dynamic programming
**Language**: CPP
> Added Create Best Time to Buy and Sell Stock with Transaction Fee

- JAVA/BucketSort.java
Bucket sort is a sorting technique in which elements are first uniformly divided into several groups called buckets. After that, elements are sorted by any sorting algorithm, and finally, it gathered the elements in a sorted manner.
> BucketSort.java

- JAVA/SEARCHING_ALGORITHM/BinarySearch.java
Here in this repo ,in  the searching algorithm in the JAVA sub-folder was not there to work on for the Binary Search Algorithm therefore i contributed that folder by adding the "BinarySearch.java" in the Java Folder.
> fixing the binary search algorithm problem in java folder

- JAVA/LINKEDLIST/DeleteNode.java
- JAVA/LINKEDLIST/LinkedList.java
There was no Linked List Operation Folder in the Java Section therefore i add the 
1.Node Insertion in singly linked list 
2.Node Deletion in singly linked list
> addded  linked list file

- PYTHON/merge_sort.py
Added Merge sort program in Python folder and followed all guidelines mentioned in README.md
> Added Merge Sort in Python

- C++/multipleconstructor.cpp
added example of various types of constructors in c++
> added multiple constructor example in c++

- C++/Linked List/Doubly LinkedList.cpp
The provided C++ code demonstrates the implementation of a doubly linked list and includes functions to perform various operations on the linked list.
> Create Doubly LinkedList.cpp

- C++/symmetric_Tree.cpp
Fixes #214 
added solution for symmetric tree in C++
> added solution for symmetric_tree in C++

- C++/Matrix multiplication.cpp
added matrix multiplication in C++
solved issue #350
> Create Matrix multiplication.cpp

- 3Sum Closest
100% memory Efficient Code in C language which is Question no 16 of Leetcode of Medium Level.
> 3Sum Closest.c

- C++/Linked List/MergeTwoSortedLists.cpp
Implement MergeTwoSortedLists function to merge two sorted linked lists in  cpp/linkedlist
> Implement MergeTwoSortedLists function to merge two sorted linked lists

- CONTRIBUTING.md
- I expanded upon and updated the contributing.md file to reflect the upcoming 2025 Hacktoberfest
- I added more detailed instructions on how to contribute
> expanded and updated the contributing.md file for this year
